version: '3.8'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=y
    ports:
      - "1433:1433"
